package EmpresaApp;


/**
* EmpresaApp/Empresa.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empresa.idl
* lunes 14 de mayo de 2018 08:07:04 PM COT
*/

public interface Empresa extends EmpresaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Empresa
