package EmpresaApp;


/**
* EmpresaApp/EmpresaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empresa.idl
* lunes 14 de mayo de 2018 08:07:04 PM COT
*/

public interface EmpresaOperations 
{
  boolean insertarEmpresa (int nit, String razon_social, String direccion, String telefono);
  String consultarEmpresa (int nit);
  boolean eliminarEmpresa (int nit);
  boolean actualizarEmpresa (int nit, String razon_social, String direccion, String telefono);
  String listarEmpresa ();
  void shutdown ();
} // interface EmpresaOperations
