package EmpresaApp;


/**
* EmpresaApp/EmpresaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empresa.idl
* lunes 14 de mayo de 2018 08:07:04 PM COT
*/

public abstract class EmpresaPOA extends org.omg.PortableServer.Servant
 implements EmpresaApp.EmpresaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarEmpresa", new java.lang.Integer (0));
    _methods.put ("consultarEmpresa", new java.lang.Integer (1));
    _methods.put ("eliminarEmpresa", new java.lang.Integer (2));
    _methods.put ("actualizarEmpresa", new java.lang.Integer (3));
    _methods.put ("listarEmpresa", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // EmpresaApp/Empresa/insertarEmpresa
       {
         int nit = in.read_long ();
         String razon_social = in.read_wstring ();
         String direccion = in.read_wstring ();
         String telefono = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarEmpresa (nit, razon_social, direccion, telefono);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // EmpresaApp/Empresa/consultarEmpresa
       {
         int nit = in.read_long ();
         String $result = null;
         $result = this.consultarEmpresa (nit);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 2:  // EmpresaApp/Empresa/eliminarEmpresa
       {
         int nit = in.read_long ();
         boolean $result = false;
         $result = this.eliminarEmpresa (nit);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // EmpresaApp/Empresa/actualizarEmpresa
       {
         int nit = in.read_long ();
         String razon_social = in.read_wstring ();
         String direccion = in.read_wstring ();
         String telefono = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarEmpresa (nit, razon_social, direccion, telefono);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // EmpresaApp/Empresa/listarEmpresa
       {
         String $result = null;
         $result = this.listarEmpresa ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 5:  // EmpresaApp/Empresa/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:EmpresaApp/Empresa:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Empresa _this() 
  {
    return EmpresaHelper.narrow(
    super._this_object());
  }

  public Empresa _this(org.omg.CORBA.ORB orb) 
  {
    return EmpresaHelper.narrow(
    super._this_object(orb));
  }


} // class EmpresaPOA
